prog: main.o Collision.o 
	gcc Collision.o main.o -o prog -lSDL -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -g
Collision.o:Collision.c
	gcc -c Collision.c -lSDL -lSDL_image -lSDL_mixer -g


